### ISSUE TITLE
Unable to get proper string from file while reading

### ISSUE THREAD

**Issue by himharsh1997** [Jaid/read-file-string#24]
I was reading a file nme al.txt which has txt as
```
my name is himanshu joshi
Algolia is a great search tool.
```

but on read using readFileStringSync I was getting something like this 

```
F�Qword/numbering.xml��MN�0�O�"��$ 5�
6����X�=��I��q��R$��U��������Kɠ�h��ˈ\3Ȅ.R���x"�uTgT��)9rK���u��J�9�}�Gh�(���9���e%W�.�p�9���/�Ce
                                                                                                ��N�����tHI�:�
                                                                                                              %��ܝ$     �`���
���Jv�*ŵ;;�ȥ��-��=Mͥ�b�C�Q+��k��
                               i��dk�f�qk��][�q4a�'Ġ���OϾE�0�t\����vF�ga�F�қ�#���.�y^ꍘ��+�W�
PIChF�Qword/settings.xml���n�0U\�Kj�H+�G{E����9��?�X��p�
                              ǟ`����I6uzX�����=#ɶ}A����'ǖդ@�f�H�?�
```

which I don't want.

Also can we also make to it get data as json base on section of files?

**Comment by Jaid** [comment]
I revisited the [tests](https://github.com/Jaid/read-file-string/blob/master/test/test.js) and could not find anything wrong.

> I was getting something like this

This package only supports UTF-8. The wrong contents could be caused by a text encoding mismatch.

> get data as json base on section of files?

If you want to load JSON, you can use `JSON.parse(readFileStringSync("file.json"))` or [read-file-json](https://github.com/Jaid/read-file-json).
